#ifndef RUBYDATASTRUCTURES_GLOBAL_H
#define RUBYDATASTRUCTURES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RUBYDATASTRUCTURES_LIBRARY)
#  define RUBYDATASTRUCTURESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RUBYDATASTRUCTURESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RUBYDATASTRUCTURES_GLOBAL_H
